<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('posts')->insert([
            'author_id' => 1,
            'title' => 'Pierwsza wyprawa w góry.',
            'content' => '<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut porttitor est quis massa fermentum, et efficitur arcu dictum. Duis maximus, tortor vitae sodales blandit, metus ligula venenatis leo, in mollis ex lorem nec erat. Fusce venenatis vel libero luctus posuere. Quisque quis lorem et nisi vehicula fringilla ac ac lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec interdum, risus quis lacinia convallis, odio mi imperdiet lacus, sed malesuada leo est vitae mauris. Aliquam consectetur finibus orci eget viverra. Nunc a tellus vel ante sollicitudin maximus in id turpis. Nulla non urna nisl. Morbi laoreet, enim eu posuere posuere, lectus velit dapibus leo, ultricies commodo ante nunc at magna. Vivamus in sem quis justo porta elementum id id mauris. Vestibulum commodo lorem sit amet mi egestas, vitae volutpat mi blandit. Morbi vehicula tempus elit, at imperdiet libero mollis vitae.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Sed nulla nunc, tempus in aliquet facilisis, dictum eget risus. Duis eu viverra mi. Curabitur mauris metus, tincidunt sed felis quis, placerat tempus arcu. Donec fermentum blandit nisi ac euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis ac vulputate nisi, at vehicula quam. Vivamus ut aliquam augue, sed feugiat tellus. Pellentesque condimentum quis ex ultrices volutpat. Mauris consectetur neque eu quam molestie, a maximus nibh varius. Nunc id faucibus augue.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Etiam cursus lacus tortor, vel dictum libero eleifend sit amet. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras ullamcorper vehicula mauris a cursus. Nunc a mauris vel erat semper consectetur. Ut ornare malesuada orci, in viverra arcu finibus vitae. Mauris ullamcorper, nulla non malesuada sodales, urna est efficitur metus, bibendum molestie turpis augue quis nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas venenatis finibus nisl a rhoncus. Praesent a nibh erat. Sed placerat sem interdum scelerisque pulvinar. Fusce eu quam dictum, dictum magna non, tincidunt erat. Vestibulum sed dui arcu. Fusce at faucibus sapien, eu suscipit nisl. Proin nec tellus elit. Quisque justo felis, blandit a suscipit a, molestie nec erat. Mauris dapibus augue sapien, a feugiat lacus dictum eget.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Etiam consectetur sapien commodo condimentum interdum. Aliquam eget elementum tellus. Etiam suscipit semper massa ac elementum. Nam bibendum mi et pulvinar finibus. Vestibulum suscipit laoreet laoreet. Maecenas elementum magna sit amet venenatis lacinia. Praesent massa nulla, condimentum in ligula at, iaculis porttitor diam. Aliquam congue efficitur ex, quis vulputate nisl imperdiet ut. Aliquam erat volutpat. Mauris mattis magna at elit ultricies efficitur.</p>
<p style="margin: 0px 0px 15px; padding: 0px; font-family: \'Open Sans\', Arial, sans-serif;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://wallpaperstream.com/wallpapers/thumbnails/mountain/Awesome-Snowy-Mountain-Wallpaper_thumb.jpg" alt="Moutains" width="800" height="450" /></p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Proin pretium imperdiet ultrices. Vivamus maximus orci purus, eu porta eros dignissim nec. Duis in congue ante. Nullam sem purus, egestas id volutpat sed, tincidunt nec lacus. Nullam ac risus quis leo congue sodales. Mauris a varius metus, in suscipit enim. Sed mollis ligula sit amet enim finibus, in posuere nulla semper. Proin efficitur volutpat ligula, imperdiet posuere dolor vehicula eu. In dui nisi, aliquet eget metus sed, dictum varius odio. Vestibulum suscipit suscipit massa, vel pellentesque erat egestas non. Aenean maximus odio in arcu mattis, quis eleifend ligula aliquam. Mauris et aliquet nibh, a rutrum ante. Ut lacinia aliquet diam, eget accumsan purus blandit non. Quisque non neque ac mi varius finibus sit amet sit amet nibh. Nam vitae dui venenatis, aliquam ex nec, congue magna.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Quisque id elit semper lectus aliquet efficitur. Nulla at odio facilisis, gravida tortor vel, accumsan metus. Nullam gravida turpis felis, sit amet vulputate purus mattis quis. Sed tristique congue magna, sed facilisis elit ultrices lobortis. Donec non justo elit. Pellentesque et quam ligula. Nullam vitae neque sollicitudin, finibus dolor id, sollicitudin metus. Ut nec lacinia orci, sit amet placerat dui. Nullam magna lectus, suscipit eget venenatis eu, mollis eget enim. Donec id lacus mollis, ullamcorper ipsum non, fermentum arcu. Donec auctor nunc eget erat placerat aliquet.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Ut enim augue, iaculis a massa sit amet, faucibus pellentesque lorem. Aenean leo ex, imperdiet ac lacus vel, porta molestie mi. Etiam consequat ullamcorper quam, eu porta nisi venenatis ac. Morbi egestas elit nec urna lobortis faucibus. Proin luctus eros ut tellus ullamcorper auctor. Mauris porttitor sapien a sollicitudin aliquet. Nam interdum euismod dui sit amet egestas. Nullam luctus ullamcorper augue et eleifend. Sed lacus arcu, sagittis cursus ornare a, feugiat eu risus.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Integer id dapibus nunc. Duis consectetur est vitae malesuada hendrerit. Integer tincidunt dictum odio, eget accumsan quam. Aliquam tortor neque, ornare at nisi sit amet, cursus finibus sapien. Suspendisse laoreet tempus molestie. Nulla interdum ultrices erat, quis aliquet eros dictum in. Aliquam dictum felis eu tincidunt posuere. Duis porttitor facilisis nisi, in cursus nibh fermentum at.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Donec dui lacus, commodo ultricies justo in, gravida aliquet sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam feugiat lacinia sollicitudin. Donec vitae magna eu ligula imperdiet porta. Nullam massa dolor, tristique porta massa quis, euismod feugiat nisl. Morbi condimentum risus a tincidunt porta. Maecenas volutpat libero vitae lectus pretium mattis. Etiam finibus augue lorem, ac consectetur purus ullamcorper non.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Maecenas augue nibh, lobortis ac quam vel, eleifend lacinia turpis. Proin aliquam nunc tempor, lacinia eros in, aliquet dolor. Praesent vitae vestibulum ante. Quisque at nibh et augue auctor sagittis. Suspendisse potenti. Donec sit amet condimentum lorem. Phasellus nec mauris sit amet nulla imperdiet fermentum a at sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer ornare porta quam, in luctus neque finibus ut. Phasellus eget nibh at enim cursus consectetur. Pellentesque massa metus, lacinia ac lorem vel, volutpat pulvinar dui. Sed vel leo ornare, pulvinar dolor a, rhoncus nibh. Maecenas nec pharetra odio, sed pharetra nulla. Maecenas posuere aliquam lectus nec mattis.</p>',
            'image_url' => 'https://i.ibb.co/DbDcC1L/beautiful-mountains-wallpaper-1920x1080.jpg',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);

        DB::table('posts')->insert([
            'author_id' => 1,
            'title' => 'Wizyta w Barcelonie.',
            'content' => '<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu tortor congue, varius sem ac, tempus diam. Donec fermentum neque tortor, et eleifend neque laoreet eu. Nam sagittis nulla sed nunc dignissim varius quis eu nisl. Nullam condimentum, odio id accumsan ornare, massa libero facilisis neque, vitae consequat neque metus nec odio. Nullam arcu lorem, tempus sit amet turpis quis, mollis fermentum orci. Donec euismod tincidunt lectus. Pellentesque mauris odio, tempus at eleifend ut, condimentum facilisis tortor. Maecenas facilisis felis eu suscipit viverra. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nunc tempus, neque non gravida bibendum, nisl nunc imperdiet diam, viverra dapibus dolor erat sit amet velit. Phasellus id posuere risus. Aliquam gravida elit dictum tortor cursus, nec bibendum sapien auctor. In hac habitasse platea dictumst. Suspendisse justo lacus, dapibus id laoreet nec, finibus id dui. Ut luctus odio sed placerat feugiat.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Morbi dapibus ornare metus vel mollis. Integer ultricies scelerisque quam non suscipit. Praesent ante tellus, imperdiet nec tempor a, dignissim quis felis. Sed augue sem, tempus ut dolor sit amet, aliquam fringilla est. Fusce id nisl vitae odio auctor tincidunt non posuere risus. Maecenas nibh neque, condimentum ut dictum ac, eleifend et odio. Duis lobortis sagittis orci. In et vestibulum eros. Fusce finibus eros massa, nec consectetur justo eleifend in. Donec sit amet dui mauris. Praesent facilisis laoreet aliquam.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Nullam turpis magna, convallis tristique accumsan et, ullamcorper vel purus. Sed dapibus vitae sem ac vulputate. Mauris gravida tincidunt orci, sed sagittis mi egestas ut. Etiam dui ex, commodo ut ornare a, pharetra sed lacus. Nam ac scelerisque velit, a scelerisque erat. Maecenas in ligula vel leo fringilla tristique sed sit amet arcu. Vivamus et volutpat tortor, vel fermentum sapien. Nunc at justo vitae turpis luctus sagittis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec commodo, diam et blandit sodales, quam ligula vestibulum urna, non tincidunt ex mauris ac massa. Donec vulputate aliquet nulla ac faucibus. Vivamus molestie diam sit amet justo auctor molestie. Nulla et malesuada elit. Donec a tristique mi. Morbi iaculis aliquet tortor a vehicula. Donec feugiat dictum est eu molestie.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Vestibulum faucibus urna metus, quis gravida orci posuere et. In porttitor ipsum sem, sit amet malesuada est imperdiet sit amet. Sed fringilla suscipit orci. Suspendisse gravida maximus est quis elementum. Curabitur aliquet elementum justo, eget vestibulum sapien ultrices ac. Sed posuere sem at pharetra placerat. Proin ut felis neque.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Pellentesque tincidunt posuere ex, eu condimentum enim tempus vel. Donec vel sapien eget lorem lobortis interdum. Quisque aliquet luctus ligula, posuere consequat eros vulputate at. Phasellus sed neque egestas, ultrices metus rutrum, pellentesque massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam quam turpis, accumsan non ornare ac, sagittis eget sapien. Phasellus risus augue, mattis sit amet scelerisque eget, pellentesque vel nisl. Etiam quis lorem ut diam porta porttitor sodales at lectus. Quisque vitae porttitor libero, ac iaculis ligula. In congue libero non volutpat elementum.</p>',
            'image_url' => 'https://wallpapercave.com/wp/wp1825755.jpg',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);

        DB::table('posts')->insert([
            'author_id' => 1,
            'title' => 'Weekend w Paryżu ze znajomymi.',
            'content' => '<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec magna metus. Etiam quis luctus nisi. Praesent in accumsan eros, id feugiat metus. Aliquam a mi sed mi ultrices accumsan. Vivamus pharetra magna id scelerisque tristique. Nullam congue purus et diam laoreet aliquet. Morbi ut mattis lorem. Sed id nisl sed ex efficitur congue et in odio. Vestibulum dapibus lorem et leo mollis, sit amet consequat erat tempor. Donec a diam eros. Sed id quam tortor. Vestibulum facilisis faucibus faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla ac nulla vehicula, tempus risus id, egestas erat.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Aliquam lobortis eu risus id scelerisque. Proin pulvinar finibus elit. Mauris varius molestie tempus. Vivamus sollicitudin volutpat fermentum. Duis ut rutrum arcu, non finibus nisl. Suspendisse in mi a lacus dapibus ullamcorper. Suspendisse potenti. Morbi varius bibendum ante, et tempor neque dapibus at. Morbi facilisis, turpis maximus interdum pretium, risus ipsum commodo justo, et luctus urna sem tristique mi. Aliquam eget tristique orci. Nullam accumsan orci dui, sed eleifend mi sagittis vitae. Aenean vel velit mi. Cras quam ipsum, dignissim sit amet urna quis, interdum euismod lacus. Nunc vestibulum lacus justo, at pellentesque odio malesuada a. Nam tincidunt nibh nec erat tempus sodales. Ut auctor lectus massa, at vulputate ante egestas in.</p>
<h4 style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Maecenas sodales, turpis nec volutpat suscipit, metus tortor eleifend nibh, vitae pretium arcu lectus sed elit.</h4>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Suspendisse blandit, elit non ultrices bibendum, lectus nulla efficitur tortor, quis dignissim lorem purus ac ipsum. Aenean sed dictum sapien. Integer vehicula eleifend gravida. Nulla quam nunc, lacinia at tempor non, feugiat ut velit. Aliquam suscipit libero metus, eu elementum ante pretium non. Maecenas at tincidunt tellus. Curabitur sodales condimentum dolor quis placerat. Ut sodales fringilla libero sed faucibus.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur finibus dolor eget lectus dictum, non consequat mi luctus. Sed ornare massa sit amet venenatis facilisis. Pellentesque efficitur eu arcu in venenatis. Nulla nec lorem neque. Fusce tristique scelerisque neque, id rutrum quam euismod sit amet. Fusce sed mollis velit, ac egestas tellus.</p>
<p style="margin: 0px 0px 15px; padding: 0px; font-family: \'Open Sans\', Arial, sans-serif;"><img style="display: block; margin-left: auto; margin-right: auto;" src="https://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1463510482/Homeaway-Eiffel-Tower-Suite-VIEWS0516.jpg" alt="" width="898" height="561" /></p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Integer nibh ex, molestie et euismod eget, dignissim in nisi. Donec facilisis eros a cursus ornare. Ut imperdiet odio vel augue accumsan dignissim. Duis ex nunc, euismod at eros vitae, volutpat condimentum magna. Nulla facilisi. Proin volutpat magna fringilla lorem sollicitudin eleifend. Maecenas bibendum neque vel viverra vehicula.</p>',
            'image_url' => 'https://pixelz.cc/wp-content/uploads/2017/11/eiffel-tower-at-sunset-paris-france-uhd-4k-wallpaper.jpg',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);

        DB::table('posts')->insert([
            'author_id' => 2,
            'title' => 'Warszawa nocą.',
            'content' => '<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque cursus nisl non urna pellentesque, eu molestie erat malesuada. Donec vitae dignissim justo, ac interdum mauris. In sapien risus, ultrices vitae tempus ac, pulvinar ac felis. Vivamus nec blandit purus. Ut nec urna lacinia, facilisis eros in, feugiat risus. Duis congue blandit enim, sed tincidunt risus vehicula fringilla. Praesent id nulla vel felis ullamcorper accumsan. Nunc malesuada felis gravida, feugiat ante vel, porta ante. Nunc facilisis nec mi et venenatis. Integer semper porta dolor vitae molestie. Duis varius purus ut ligula porta porttitor. Nulla hendrerit posuere mi, efficitur hendrerit nunc lobortis ac.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Phasellus eget erat quis felis scelerisque blandit. Integer tempus vestibulum leo, a euismod magna semper sit amet. Phasellus elementum pharetra dui sed consequat. Morbi sagittis volutpat leo eu porttitor. Duis condimentum vel nulla et fermentum. Proin sit amet enim ligula. Morbi iaculis consequat quam iaculis elementum. In pellentesque purus nec nulla varius pharetra. Vestibulum et eros vitae tellus suscipit auctor. Duis purus tortor, consectetur non auctor non, euismod et justo. Nulla facilisi. Quisque hendrerit malesuada blandit. Phasellus nec posuere eros, eu luctus orci. Etiam convallis nibh vel malesuada accumsan. Integer fermentum mauris et sem pretium, vel dictum neque venenatis. Aliquam non tincidunt urna.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Etiam ut velit in dui lobortis pellentesque. Pellentesque pulvinar ex vitae est fringilla, ullamcorper auctor dui luctus. Vivamus sollicitudin sed leo non scelerisque. In sed accumsan purus. Vestibulum orci mauris, rutrum vel eleifend vel, molestie consequat odio. Fusce mi ante, faucibus ac massa ut, commodo bibendum arcu. Maecenas cursus, mi eu pretium ultrices, est lacus lacinia urna, vitae ultricies risus sapien in ex. Praesent eget metus dolor.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Nam eget quam magna. Ut suscipit semper ex, vel consequat mauris vehicula id. Quisque id feugiat nibh, eget tristique ligula. Suspendisse sit amet enim at lorem varius pharetra. Donec imperdiet iaculis consectetur. Vestibulum ac volutpat enim, id interdum tellus. Vestibulum mattis varius arcu quis viverra. Morbi a risus justo. Aenean porta diam a luctus viverra. Aenean in lobortis nunc.</p>
<p style="margin: 0px 0px 15px; padding: 0px; text-align: justify; font-family: \'Open Sans\', Arial, sans-serif;">Sed pellentesque nibh felis, eget imperdiet libero finibus vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam nec fringilla ex, id auctor turpis. Donec pretium ac nulla scelerisque suscipit. Quisque consequat tristique erat pulvinar laoreet. Maecenas magna velit, efficitur vel magna non, interdum tincidunt sem. Integer a consectetur orci, vel egestas massa. Morbi pretium dolor sit amet risus semper vehicula.</p>',
            'image_url' => 'https://images.unsplash.com/photo-1519197924294-4ba991a11128',
            'created_at' => Carbon::now()->format('Y-m-d H:i:s')
        ]);
    }
}
